title: Oude RKZ Groningen
author:
  name: Tom Blauwendraat
  email: 'antiflu@gmail.com'
metadata:
  description: 'Het Oude RKZ is een woongemeenschap in Groningen'
  'og:image': 'https://www.orkz.net/user/themes/ouderkz/images/logo2.png'

